name: Java Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Jar
        run: |
          mvn package
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/target" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: io-project-architecture-0.12.jar
          path: ${{ env.artifactPath }}/io-project-architecture-0.12.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.tag_version.outputs.new_tag }}
          prerelease: true
          title: Release ${{ steps.tag_version.outputs.new_tag }}
          files: ${{ env.artifactPath }}/io-project-architecture-0.12.jar
      - name: generate Javadoc
        run: |
          mvn javadoc:javadoc
          echo "javadocPath=$(pwd)/target/site/apidocs" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: JSON-tools-${{ env.RELEASE_VERSION }}.jar
          path: ${{ env.artifactPath }}/JSON-tools-${{ env.RELEASE_VERSION }}.jar
      - uses: actions/upload-artifact@v3
        with:
          name: JSON-tools-${{ env.RELEASE_VERSION }}-javadoc
          path: ${{ env.javadocPath }}